### ISSUE TITLE
How do I run it

### ISSUE THREAD

**Issue by wjzhang-ty** [bionicvisionlab/2021-HBA-U-Net#1]
I found your work on PaperWithCode and it was outstanding! 
As a novice I want to learn your work, but I can't run it, is this project complete?

**Comment by mbeyeler** [comment]
Hi! https://github.com/bionicvisionlab/2021-HBA-U-Net/blob/master/HBA_U_Net.py provides the code to create HBA-U-Net with Keras, but you will have to separately acquire the dataset and run `model.compile()` and `model.fit()` yourself

**Comment by wjzhang-ty** [comment]
I understand. Thank you for your reply！
